import { mkdir, writeFile } from 'node:fs/promises'
import { resolve, relative, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { getTableName } from 'drizzle-orm'

export interface GenerateOptions {
  schema: string
  out?: string
  table?: string
  dryRun?: boolean
}

export interface GeneratedFile {
  path: string
  content: string
}

function isTable(value: unknown): boolean {
  if (!value || typeof value !== 'object') return false
  try {
    getTableName(value as Parameters<typeof getTableName>[0])
    return true
  } catch {
    return false
  }
}

function toSingular(name: string): string {
  if (name.endsWith('ies')) return name.slice(0, -3) + 'y'
  if (name.endsWith('s') && !name.endsWith('ss')) return name.slice(0, -1)
  return name
}

function toWords(name: string): string[] {
  return name
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .toLowerCase()
    .split(/[_\s-]+/)
    .filter(Boolean)
}

function toFactoryVarName(tableName: string): string {
  const singular = toSingular(tableName)
  const words = toWords(singular)
  const camel = words
    .map((w, i) => (i === 0 ? w : w[0]!.toUpperCase() + w.slice(1)))
    .join('')
  return camel + 'Factory'
}

function toFileName(tableName: string): string {
  const singular = toSingular(tableName)
  const words = toWords(singular)
  return words.join('-') + '.factory.ts'
}

function renderFactory(
  factoryVar: string,
  exportName: string,
  schemaRelPath: string,
): string {
  const importPath = schemaRelPath.replace(/\.ts$/, '.js')
  return [
    `// Auto-generated by drizzle-fixtures. Do not edit manually.`,
    ``,
    `import { defineFactory } from 'drizzle-fixtures'`,
    `import { ${exportName} } from '${importPath}'`,
    ``,
    `export const ${factoryVar} = defineFactory(${exportName})`,
    ``,
  ].join('\n')
}

function renderIndex(exports: Array<{ factoryVar: string; fileName: string }>): string {
  const lines = [
    `// Auto-generated by drizzle-fixtures. Do not edit manually.`,
    ``,
  ]
  for (const { factoryVar, fileName } of exports) {
    const base = fileName.replace(/\.ts$/, '')
    lines.push(`export { ${factoryVar} } from './${base}.js'`)
  }
  lines.push(``)
  return lines.join('\n')
}

export async function generate(opts: GenerateOptions): Promise<GeneratedFile[]> {
  const schemaPath = resolve(opts.schema)
  const schemaUrl = pathToFileURL(schemaPath).href

  const mod = await import(schemaUrl) as Record<string, unknown>

  const tables: Array<{ exportName: string; tableName: string }> = []
  for (const [exportName, value] of Object.entries(mod)) {
    if (!isTable(value)) continue
    const tableName = getTableName(value as Parameters<typeof getTableName>[0])
    if (opts.table && tableName !== opts.table) continue
    tables.push({ exportName, tableName })
  }

  if (tables.length === 0) {
    console.warn('[drizzle-fixtures] No tables found in schema.')
    return []
  }

  const outDir = opts.out ? resolve(opts.out) : undefined
  const files: GeneratedFile[] = []
  const indexEntries: Array<{ factoryVar: string; fileName: string }> = []

  for (const { exportName, tableName } of tables) {
    const factoryVar = toFactoryVarName(tableName)
    const fileName = toFileName(tableName)

    let schemaRelPath: string
    if (outDir) {
      const rel = relative(outDir, schemaPath)
      schemaRelPath = rel.startsWith('.') ? rel : `./${rel}`
    } else {
      schemaRelPath = `./${schemaPath}`
    }

    const content = renderFactory(factoryVar, exportName, schemaRelPath)
    const filePath = outDir ? join(outDir, fileName) : fileName

    files.push({ path: filePath, content })
    indexEntries.push({ factoryVar, fileName })
  }

  const indexContent = renderIndex(indexEntries)
  const indexPath = outDir ? join(outDir, 'index.ts') : 'index.ts'
  files.push({ path: indexPath, content: indexContent })

  if (!opts.dryRun && outDir) {
    await mkdir(outDir, { recursive: true })
    for (const file of files) {
      await writeFile(file.path, file.content, 'utf8')
    }
    console.log(`✓ Generated ${files.length - 1} ${files.length - 1 === 1 ? 'factory' : 'factories'} → ${opts.out}`)
  } else if (opts.dryRun) {
    for (const file of files) {
      console.log(`\n--- ${file.path} ---\n${file.content}`)
    }
  }

  return files
}
